version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore BrumWithMe/BrumWithMe.sln
build:
  project: BrumWithMe/BrumWithMe.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: phzoOBpzRlLWwSsiaXoAEKKzToGvIvezY4Wvd

after_test:
  - BrumWithMe\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"BrumWithMe\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single BrumWithMe\Tests\BrumWithMe.Services.Data.Tests\bin\Debug\BrumWithMe.Services.Data.Tests.dll BrumWithMe\Tests\BrumWithMe.Services.Providers.Tests\bin\Debug\BrumWithMe.Services.Providers.Tests.dll" -output:cover.xml

  - BrumWithMe\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml